title: Critique of Pure Slurp
description: Personal website.  

author:
  name: Yousuf Khan

minima:
  social_links:
    - { icon: "envelope", title: "Email", url: "mailto:yousufshah.khan@mail.utoronto.ca" }
    - { icon: "github", title: "GitHub", url: "https://github.com/yousufk1729" }
    - { icon: "linkedin", title: "LinkedIn", url: "https://www.linkedin.com/in/yousuf-khan-12569431b" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  quiet_deps: true
  silence_deprecations: [import]