title: Critique of Pure Slurp
description: Personal website.  

author:
  name: Yousuf Khan
  email: yousufshah.khan@mail.utoronto.ca

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  quiet_deps: true
  silence_deprecations: [import]